### ISSUE TITLE
New Maintainer TODO List

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#504]
I figure I may as well keep this public and easy to access and comment on.  So here's my TODO list for getting this new era of maintainership up to speed and then keep it going.

- [x] Update `update_feed` URL
- [x] Initial python 2.7 based release that is 3.43 with *only* the necessary changes in config.py to be 3.4.4.0 / 3.44 and change the update_feed URL.
- [x] Request Otis to point the current update_feed URL contents at this new 3.44 release.  This will then mean all currently running clients will eventually offer the upgrade. *Request made, awaiting response/action.*
- [x] Ensure any "only Windows 10" language emphasises that is about testing and no guarantee the app will work on older Windows OS.
- [x] Make a PR to https://github.com/EDCD/EDCD.github.io to get the URL for EDMC changed.
- [x] Update EDDN `CLIENT_ID`
- [x] ~~Run the scripts to update stations.p et al~~ `eddb.py` needs 64-bit, and takes forever.  themroc has now kindly added a "system by name" URL format to eddb.io, so we won't even need systems.p in the future. For now just release with the old files and look into switching over to the by-name lookups for eddb on systems.
- [x] Address outstanding PRs, starting with those fixing bugs, and the ones adding things like the `CarrierJump` journal event support.
- [x] Tweak the python 2.7 plugin code to check if plugins have a `plugin_start3()` available, and for those that don't list them in a popup and/or on the settings plugin page.  This is so as to alert people if they're using plugins that won't work after the migration to python 3.7.
- [x] Add a tag to denote the final python 2.7 code.
- [x] Make that one last python 2.7 release with the "will be outdated" plugin check.

- [x] Bring the python3 branch fully in line with any additional commits made to the master branch since that 3.50 preview release.
- [x] Ensure the python3 branch has functional parity with the last released code from the master (python 2.7) branch
- [x] Update requirements.txt to match what works with the py2exe build.
- [x] Merge the python3 branch into master.
- [x] Address any other outstanding PRs.
- [x] Close any outstanding Issues we're sure have been addressed by code changes (where that didn't happen anyway due to addressing PRs).
- [x] Close any outstanding issues with too little information/can't reproduce.
- [x] Clean up all of the documentation.  Pare down README.md to the bare necessities with other sections getting their own file under docs/.  This will include the RELEASING.md I've been putting together as a detailed guide to getting the .exe and .msi files built on Windows 10.

**Comment by Athanasius** [comment]
I've re-ordered things a little.

The plan is now to get any actual bugfixes and necessary enhancements (like adding support for the `CarrierJump` event) to the Python 2.7 code before that final release.  *Then* I'll move on to getting a Python 3.7 release done.
